# Default values for chremoas-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

#configNamespace: default
serviceAccountName: roach-dev-cockroachdb
chremoasDBUser: chremoas

pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

services:
  - name: micro-web
    type: ClusterIP
    port: 80
    targetPort: 8082
  - name: auth-web
    type: ClusterIP
    port: 80
    targetPort: 3000

auth_web_fqdn: chremoas.4amlunch.net

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Service Specific Values

# This should *never* have its replicas set to more than 1. Not until we implement some manner of
# master/slave controls
chremoas:
  image: chremoas/chremoas
  tag: v1.2.5
  replicas: 1

# This needs to be 1 the first time you start the service so you can accept the CSR for CockroachDB.
# Don't increase this until after you've done that or bad things will happen according to the docs.
auth_srv:
  image: chremoas/auth-srv
  tag: v1.2.6
  replicas: 1
  initCertsVersion: 0.4

micro_web:
  image: microhq/micro
  tag: latest
  replicas: 1

serviceList:
  - name: auth-cmd
    repository: chremoas
    tag: v1.2.5
  - name: auth-esi-poller
    repository: chremoas
    tag: v1.2.5
  - name: auth-web
    repository: chremoas
    tag: v1.2.6
  - name: discord-gateway
    repository: chremoas
    tag: v1.2.5
  - name: esi-srv
    repository: chremoas
    tag: v1.2.5
  - name: filter-cmd
    repository: chremoas
    tag: v1.2.5
  - name: lookup-cmd
    repository: chremoas
    tag: v1.2.5
  - name: perms-cmd
    repository: chremoas
    tag: v1.2.5
  - name: perms-srv
    repository: chremoas
    tag: v1.2.5
  - name: role-cmd
    repository: chremoas
    tag: v1.2.5
  - name: role-srv
    repository: chremoas
    tag: v1.2.7
  - name: sig-cmd
    repository: chremoas
    tag: v1.2.5
