# Default values for chremoas-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configNamespace: com.aba-eve
chremoasDBUser: chremoas_aba

pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

services:
  - name: micro-web
    type: ClusterIP
    port: 80
    targetPort: 8082
  - name: auth-web
    type: ClusterIP
    port: 80
    targetPort: 3000

auth_web_fqdn: discord.aba-eve.com
#auth_web_fqdn: chremoas-dev.4amlunch.net

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 5Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#micro_web:
#  image: microhq/micro
#  tag: latest
#  replicas: 1

serviceList:
  # This should *never* have its replicas set to more than 1. Not until we implement some manner of
  # master/slave controls
  - name: chremoas
    repository: chremoas
    tag: v1.3.3
    replicas: 1
  - name: discord-gateway
    repository: chremoas
    tag: v1.3.8
    replicas: 1
  - name: auth-esi-poller
    repository: chremoas
    tag: v1.3.4
    replicas: 1
  - name: auth-web
    repository: chremoas
    tag: v1.3.3
    replicas: 1
  - name: auth-srv
    repository: chremoas
    tag: v1.3.2
    replicas: 1
  - name: esi-srv
    repository: chremoas
    tag: v1.3.3
    replicas: 2
  - name: perms-srv
    repository: chremoas
    tag: v1.3.3
    replicas: 2
  - name: role-srv
    repository: chremoas
    tag: v1.3.3
    replicas: 2
  - name: auth-cmd
    repository: chremoas
    tag: v1.3.4
    replicas: 2
  - name: filter-cmd
    repository: chremoas
    tag: v1.3.2
    replicas: 2
  - name: lookup-cmd
    repository: chremoas
    tag: v1.3.2
    replicas: 1
  - name: perms-cmd
    repository: chremoas
    tag: v1.3.2
    replicas: 2
  - name: role-cmd
    repository: chremoas
    tag: v1.3.2
    replicas: 2
  - name: sig-cmd
    repository: chremoas
    tag: v1.3.1
    replicas: 2
