apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace}}
  name: {{ $.Release.Name }}-chremoas
  labels:
    name: {{ $.Release.Name }}-chremoas
{{ include "chremoas-helm.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.chremoas.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chremoas-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chremoas-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        name: {{ $.Release.Name }}-chremoas
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Values.serviceAccountName }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 9 }}
    {{- end }}
      containers:
        - name: chremoas
          image: "{{ .Values.chremoas.image }}:{{ .Values.chremoas.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONSUL
              value: $(HOST_IP):8500
            - name: MICRO_REGISTRY_ADDRESS
              value: $(HOST_IP):8500
            - name: MICRO_CLIENT_REQUEST_TIMEOUT
              value: 5m
            - name: MICRO_REGISTRY
              value: consul
            - name: CONFIG_NAMESPACE
              value: {{ .Release.Name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 0
      volumes:
        - name: client-certs
          emptyDir: {}

