apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-auth-web
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.auth_web_fqdn }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-auth-web
              servicePort: auth-web