apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-{{ .Values.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
